FROM jboss/base-jdk:8
MAINTAINER mohanerra@gmail.com

LABEL io.k8s.description="Platform for building and running JBoss applications" \
      io.k8s.display-name="JBoss with jdk8" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,jboss" \
      io.openshift.s2i.destination="/opt/app" \
      io.openshift.s2i.scripts-url=image:///usr/local/s2i

RUN adduser --system -u 10001 jboss

RUN mkdir -p /opt/app && mkdir -p /usr/local/s2i  && chown -R jboss: /opt/app

COPY ./S2iScripts/ /usr/local/s2i

USER 10001

EXPOSE 8080

CMD ["/usr/local/s2i/usage"]